version: 2

# Project metadata
project_name: PandaBrew

# Run before building
before:
  hooks:
    - go mod tidy
    - go mod verify
    - go test -v ./...
    - go run ./cmd/gendocs
    - bash -c 'for f in manpages/*.1; do [ -f "$f" ] && gzip -f "$f"; done || true'

# Build configuration
builds:
  - id: pandabrew
    binary: pandabrew
    main: ./cmd/pandabrew
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w"
      - "-X main.version={{.Version}}"
      - "-X main.commit={{.Commit}}"
      - "-X main.date={{.Date}}"
      - "-X main.builtBy=goreleaser"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm64

# Archive configuration
archives:
  - id: pandabrew-archive
    ids:
      - pandabrew
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - docs/**/*
      - src: manpages/*.gz
        dst: share/man/man1/
        strip_parent: true
    # Default format for all platforms
    formats:
      - tar.gz
    # Override format for specific platforms
    format_overrides:
      - goos: windows
        formats:
          - zip

# Checksum configuration
checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# GitHub Release configuration
release:
  github:
    owner: KazeFreeze
    name: PandaBrew
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## PandaBrew {{ .Tag }}

    🐼☕ Project file extraction made delightful!

    ### Installation

    #### Linux/macOS
    ```bash
    # Download and extract
    tar -xzf PandaBrew_{{ .Version }}_{{ .Os }}_{{ .Arch }}.tar.gz

    # Move to PATH
    sudo mv pandabrew /usr/local/bin/

    # Install man pages (optional)
    sudo mkdir -p /usr/share/man/man1
    sudo cp share/man/man1/*.gz /usr/share/man/man1/

    # Make executable (if needed)
    sudo chmod +x /usr/local/bin/pandabrew
    ```

    #### Windows
    Extract the ZIP file and add the directory to your PATH.

    #### Package Managers
    See [INSTALLATION.md](https://github.com/KazeFreeze/PandaBrew/blob/main/docs/INSTALLATION.md) for Homebrew and AUR installation.

    ### Documentation
    - 📖 [CLI Reference](https://github.com/KazeFreeze/PandaBrew/blob/main/docs/CLI_REFERENCE.md)
    - 🚀 [Installation Guide](https://github.com/KazeFreeze/PandaBrew/blob/main/docs/INSTALLATION.md)
    - 📚 Man pages included in archive

  footer: |
    ---

    **Full Changelog**: https://github.com/KazeFreeze/PandaBrew/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### What's Included
    - Binary executable for your platform
    - Complete documentation in `docs/` directory
    - Man pages (Linux/macOS in `share/man/man1/`)
    - README and LICENSE

# Linux packages (deb, rpm, apk) and AUR
nfpms:
  - id: pandabrew-package
    package_name: pandabrew
    ids:
      - pandabrew
    homepage: https://github.com/KazeFreeze/PandaBrew
    description: |
      A TUI tool for selective file extraction and project documentation.
      Supports conventional commits and exports project structures with smart filtering.
    maintainer: Bernard Tapiru, Jr. <tapirua@gmail.com>
    license: MIT
    vendor: Bernard Tapiru, Jr.
    formats:
      - archlinux
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    # Install documentation and man pages
    contents:
      - src: README.md
        dst: /usr/share/doc/pandabrew/README.md
      - src: LICENSE
        dst: /usr/share/licenses/pandabrew/LICENSE
      - src: docs/CLI_REFERENCE.md
        dst: /usr/share/doc/pandabrew/CLI_REFERENCE.md
        file_info:
          mode: 0644
      - src: docs/INSTALLATION.md
        dst: /usr/share/doc/pandabrew/INSTALLATION.md
        file_info:
          mode: 0644
      - src: docs/*.md
        dst: /usr/share/doc/pandabrew/
      - src: manpages/*.gz
        dst: /usr/share/man/man1/
    # Post-install script to update man database
    scripts:
      postinstall: |
        #!/bin/sh
        if command -v mandb > /dev/null 2>&1; then
          mandb -q
        fi

# Homebrew tap
brews:
  - name: pandabrew
    repository:
      owner: KazeFreeze
      name: homebrew-tap
      branch: main
    ids:
      - pandabrew
    homepage: https://github.com/KazeFreeze/PandaBrew
    description: "A TUI tool for selective file extraction and project documentation"
    license: "MIT"
    # Install binary, documentation, and man pages
    install: |
      bin.install "pandabrew"
      doc.install "README.md"
      doc.install "LICENSE"
      doc.install Dir["docs/*"]
      man1.install Dir["share/man/man1/*.gz"]
    test: |
      system "#{bin}/pandabrew", "--version"
    dependencies:
      - name: go
        type: build

# Snapcraft configuration
snapcrafts:
  - id: pandabrew-snap
    name: pandabrew
    summary: Project file extraction tool with TUI
    description: |
      PandaBrew is a high-performance, headless-first tool to extract
      codebases into a single text file for LLM context. Features an
      interactive TUI with workspace management and smart file filtering.
    grade: stable
    confinement: strict
    license: MIT
    base: core22
    apps:
      pandabrew:
        command: pandabrew
        plugs:
          - home
          - removable-media
          - network

# Announcements
announce:
  skip: "{{gt .Patch 0}}" # Skip announcements for patch releases
