# .github/workflows/build-and-release.yml

name: Build and Release Executable

# --- Trigger ---
on:
  push:
    tags:
      - "v*.*.*"

# --- Permissions ---
# This block grants the GITHUB_TOKEN the necessary permission to create a release.
permissions:
  contents: write

jobs:
  build:
    # --- Strategy Matrix ---
    # Define the different operating systems and corresponding build targets.
    strategy:
      matrix:
        include:
          - os: windows-latest
            build_target: windows
            asset_name: PandaBrew-windows.zip
            executable_path: dist/PandaBrew.exe
          - os: ubuntu-latest
            build_target: fedora
            asset_name: PandaBrew-fedora.zip
            executable_path: dist/PandaBrew

    # --- Runner ---
    runs-on: ${{ matrix.os }}

    steps:
      # --- 1. Checkout Code ---
      # This step checks out a copy of your repository onto the runner.
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- 2. Set up Python ---
      # This step installs a specific version of Python.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # --- 3. Install Dependencies (Windows) ---
      - name: Install Windows dependencies
        if: matrix.build_target == 'windows'
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      # --- 4. Build Executable (Windows) ---
      - name: Build Windows executable with PyInstaller
        if: matrix.build_target == 'windows'
        run: |
          pyinstaller `
            --name "PandaBrew" `
            --onefile `
            --windowed `
            --icon "pandabrew.ico" `
            main.py

      # --- 5. Build Executable (Fedora) ---
      # We run this on an ubuntu runner but execute the build inside a Fedora Docker container.
      - name: Build Fedora executable with PyInstaller
        if: matrix.build_target == 'fedora'
        run: |
          docker run --rm -v "${{ github.workspace }}":/app -w /app fedora:latest bash -c " \
            echo 'Installing build dependencies in Fedora container...' && \
            dnf install -y python3-pip python3-devel gcc zip python3-tkinter && \
            echo 'Installing application requirements...' && \
            pip3 install --no-cache-dir -r requirements.txt && \
            echo 'Installing PyInstaller...' && \
            pip3 install --no-cache-dir pyinstaller && \
            echo 'Building executable...' && \
            pyinstaller \
              --name PandaBrew \
              --onefile \
              --windowed \
              --icon pandabrew.ico \
              --hidden-import=PIL._tkinter_finder \
              main.py \
          "
      
      # --- 6. Package the Executable (Windows) ---
      - name: Package Windows executable
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path ${{ matrix.executable_path }} -DestinationPath ${{ matrix.asset_name }}
        shell: pwsh

      # --- 7. Package the Executable (Fedora) ---
      - name: Package Fedora executable
        if: matrix.os == 'ubuntu-latest'
        run: zip -j ${{ matrix.asset_name }} ${{ matrix.executable_path }}
      
      # --- 8. Create GitHub Release and Upload Assets ---
      # This step creates the release and uploads the zipped executable as an asset.
      # It runs for each job in the matrix, adding its asset to the same release.
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.asset_name }}
          name: "Release ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          body: "Official release of PandaBrew, version ${{ github.ref_name }}."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
