# .github/workflows/build-and-release.yml

name: Build and Release Executable

# --- Trigger ---
# This workflow runs on pushes to the main branch and on manual dispatch.
on:
  push:
    branches:
      - main
  workflow_dispatch:

# --- Permissions ---
# Enhanced permissions for semantic release
permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  # --- Semantic Release Job ---
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    outputs:
      new-release-published: ${{ steps.semantic.outputs.new-release-published }}
      new-release-version: ${{ steps.semantic.outputs.new-release-version }}
      new-release-git-tag: ${{ steps.semantic.outputs.new-release-git-tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for semantic-release to find previous tags.
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install semantic-release dependencies
        run: |
          npm install --no-save semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      - name: Create .releaserc.json
        run: |
          cat > .releaserc.json << 'EOF'
          {
            "branches": ["main"],
            "tagFormat": "v${version}",
            "repositoryUrl": "https://github.com/${{ github.repository }}",
            "plugins": [
              [
                "@semantic-release/commit-analyzer",
                {
                  "releaseRules": [
                    {"type": "feat", "release": "minor"},
                    {"type": "fix", "release": "patch"},
                    {"type": "perf", "release": "patch"},
                    {"breaking": true, "release": "major"}
                  ]
                }
              ],
              "@semantic-release/release-notes-generator",
              [
                "@semantic-release/changelog",
                {
                  "changelogFile": "CHANGELOG.md"
                }
              ],
              [
                "@semantic-release/git",
                {
                  "assets": ["CHANGELOG.md"],
                  "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
                }
              ],
              [
                "@semantic-release/github",
                {
                  "assets": []
                }
              ]
            ]
          }
          EOF

      - name: Run semantic release
        id: semantic
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # --- Build Job ---
  build:
    name: Build Executables
    needs: semantic-release
    if: needs.semantic-release.outputs.new-release-published == 'true'

    # --- Strategy Matrix ---
    # Define the different operating systems, architectures, and corresponding build targets.
    strategy:
      matrix:
        include:
          - os: windows-latest
            build_target: windows
            asset_name: PandaBrew-windows.exe
            executable_path: dist/PandaBrew.exe
          - os: ubuntu-latest
            build_target: fedora-x86_64
            asset_name: PandaBrew-fedora-x86_64
            executable_path: dist/PandaBrew
          - os: ubuntu-latest
            build_target: linux-aarch64
            asset_name: PandaBrew-linux-aarch64
            executable_path: dist/PandaBrew

    # --- Runner ---
    runs-on: ${{ matrix.os }}

    steps:
      # --- 1. Checkout Code ---
      # This step checks out a copy of your repository onto the runner.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.semantic-release.outputs.new-release-git-tag }}

      # --- 2. Set up QEMU for ARM emulation ---
      # This is necessary to build for aarch64 on an x86_64 runner.
      # It will only run on the Linux-based runners.
      - name: Set up QEMU
        if: matrix.os == 'ubuntu-latest'
        uses: docker/setup-qemu-action@v3

      # --- 3. Set up Python (for Windows build) ---
      # This step installs a specific version of Python on the host runner.
      # It's primarily for the Windows build which doesn't use Docker.
      - name: Set up Python
        if: matrix.build_target == 'windows'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # --- 4. Install Dependencies (Windows) ---
      - name: Install Windows dependencies
        if: matrix.build_target == 'windows'
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      # --- 5. Build Executable (Windows) ---
      - name: Build Windows executable with PyInstaller
        if: matrix.build_target == 'windows'
        run: |
          pyinstaller `
            --name "PandaBrew" `
            --onefile `
            --windowed `
            --icon "pandabrew.ico" `
            main.py

      # --- 6. Build Executable (Fedora x86_64) ---
      # We run this on an ubuntu runner but execute the build inside a Fedora Docker container.
      - name: Build Fedora (x86_64) executable with PyInstaller
        if: matrix.build_target == 'fedora-x86_64'
        run: |
          docker run --rm -v "${{ github.workspace }}":/app -w /app fedora:latest bash -c " \
            echo 'Installing build dependencies in Fedora container...' && \
            dnf install -y python3-pip python3-devel gcc zip python3-tkinter && \
            echo 'Installing application requirements...' && \
            pip3 install --no-cache-dir -r requirements.txt && \
            echo 'Installing PyInstaller...' && \
            pip3 install --no-cache-dir pyinstaller && \
            echo 'Building executable...' && \
            pyinstaller \
              --name PandaBrew \
              --onefile \
              --windowed \
              --icon pandabrew.ico \
              --hidden-import=PIL._tkinter_finder \
              main.py \
          "

      # --- 7. Build Executable (Linux aarch64) ---
      # This runs on an ubuntu runner but builds inside a Debian aarch64 container using QEMU.
      - name: Build Linux (aarch64) executable with PyInstaller
        if: matrix.build_target == 'linux-aarch64'
        run: |
          docker run --rm --platform linux/arm64 -v "${{ github.workspace }}":/app -w /app arm64v8/debian:bullseye bash -c " \
            echo 'Updating package list in Debian aarch64 container...' && \
            apt-get update && \
            echo 'Installing build dependencies...' && \
            apt-get install -y --no-install-recommends python3 python3-pip python3-tk python3-dev gcc zip && \
            echo 'Installing application requirements...' && \
            pip3 install --no-cache-dir -r requirements.txt && \
            echo 'Installing PyInstaller...' && \
            pip3 install --no-cache-dir pyinstaller && \
            echo 'Building executable...' && \
            pyinstaller \
              --name PandaBrew \
              --onefile \
              --windowed \
              --icon pandabrew.ico \
              --hidden-import=PIL._tkinter_finder \
              main.py \
          "

      # --- 8. Rename Executable for Upload ---
      - name: Rename executable for upload
        run: |
          if [ "${{ matrix.build_target }}" = "windows" ]; then
            # Windows: Copy and rename
            cp "${{ matrix.executable_path }}" "${{ matrix.asset_name }}"
          else
            # Linux: Copy and rename
            cp "${{ matrix.executable_path }}" "${{ matrix.asset_name }}"
            # Make sure it's executable
            chmod +x "${{ matrix.asset_name }}"
          fi
        shell: bash

      # --- 9. Upload Assets to Release ---
      # This step uploads the zipped executable as an asset to the existing release.
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.asset_name }}
          tag_name: ${{ needs.semantic-release.outputs.new-release-git-tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
